format = """
$directory\
$git_branch\
$git_status\
$git_state\
$git_commit\
$newline
$character
"""

add_newline = true

[git_commit]
commit_hash_length = 6
tag_symbol = "🔖 "
tag_disabled = false
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"

[git_status]
stashed = "📦"
