Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
