Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/EmptyMethod:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
Layout/ArrayAlignment:
  Enabled: false
Layout/LineLength:
  Max: 140
Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 15
Metrics/MethodLength:
  Max: 500
Metrics/BlockLength:
  Max: 1000
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Max: 10000
Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
