vim.keymap.set({'n'},      '<Leader>t', ':Files<CR>',    {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>b', ':Buffer<CR>',   {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>l', ':BLines<CR>',   {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>L', ':Lines<CR>',    {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>T', ':Tags<CR>',     {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>h', ':History<CR>',  {expr = false, noremap = true, silent = true})
vim.keymap.set({'n'},      '<Leader>C', ':Commits<CR>',  {expr = false, noremap = true, silent = true})
vim.keymap.set({'n', 'v'}, '<Leader>c', ':BCommits<CR>', {expr = false, noremap = true, silent = true})
