" wildignore
set wildignore+=**/node_modules
set wildignore+=**/logs
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem,*.woff,*.woff2
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz
set wildignore+=*.jpg,*.jpeg,*.png,*.gif
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*
set wildignore+=*/app/assets/*,*/tmp/cache/*
set wildignore+=*/tmp/*
set wildignore+=**.swp,*~,._*
